### ISSUE TITLE
RPI 4 display shutdown and sleep

### ISSUE THREAD

**Issue by bugsounet** [bugsounet/MMM-NewPIR#10]
Hi, i need help for command to turn on / turn off HDMI monitor with RPI 4

I want to integrate it but i have not RPI 4 for test this.

Thx

**Comment by renzo79** [comment]
I have one! How can I help you?

Best

Daniel

**Comment by bugsounet** [comment]
i search the RPI4 command to turn on / turn off for deep sleep screen.

in RPI3 : i use `vcgencmd display_power` but in RPI4 it don't work

so, what command do you use for do this ?

**Comment by hweigel** [comment]
Dunno if that helps but with Raspian Buster on a 4 week old RPI4 (4GB model) the command 
`vcgencmd display_power` 
returns
`display_power=1` when the screen is on and 
`display_power=0` when the screen is off.

The screen is turned off by NewPIR, and seems to work here regardless of rpi4 being set to false or true. I do run "force: true", though I can't even recall why I put it there.

**Comment by bugsounet** [comment]
i use this model for checking since a long time
but ... it's depend of RPI4 firmware.
Some firmware it works ... and next firmware don't work
that's why i try why another routine (dpms) with `rpi4: true`

**Comment by hweigel** [comment]
Guess I'm the lucky one, because it works for me either way. 

For those Raspberry Pi 4 users affected, try updating the operating system **including** its firmware and kernel:

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo reboot
sudo rpi-update
sudo reboot
```
