### ISSUE TITLE
Module interfering with Default Weather module

### ISSUE THREAD

**Issue by Panda-3** [bugsounet/MMM-NewPIR#11]
Hi,

When I use this module it stops my weather from loading up, but as soon as this module is disabled it works again.

**Comment by bugsounet** [comment]
hi, what is your weather module ?

**Comment by Panda-3** [comment]
Sure this is the config for the two modules
`  {
    module: "currentweather",
    position: "top_center",
    config: {
      location: "#",
      locationID: "#",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
      appid: "#",
      units: "metric",
      roundTemp: true,
      showWindDirection: false,
      showWindDirectionAsArrow: false,
      useLocationAsHeader: true
    }
  },
{
module: 'MMM-NewPIR',
position: "bottom_center",
config: {
  useSensor: false,
  sensorPin: 21,
  reverseValue: false,
  delay: 300000,
  turnOffDisplay: true,
  ecoMode: true,
  governor: "",
  debug: false
}`

**Comment by bugsounet** [comment]
i test with your config and it works weired,
attention : one bracket missing in NewPIR config

possibly try to position on top_left and activate debug: true (a counter should appear)

**Comment by Panda-3** [comment]
Woops I forgot that bracket when i pasted the code. I have tried what you have suggested, this is the result 

![mirror](https://user-images.githubusercontent.com/4959525/75135864-c8350a80-56da-11ea-86b7-9a27166fc454.PNG)

**Comment by bugsounet** [comment]
Ok, please wait next update (env 15 min.)
Maybe, weather refuse the connection on start (start loading all module at the same time take a time for internet data receive) 

So, in next interval update it will be ok

**Comment by Panda-3** [comment]
This is really weird it seems to have fixed it self and works fine now. It may have been the interval update but it wasn't working for a few hours 🤷‍♂ 
I will close this issue now, thank you for all your help!
