### ISSUE TITLE
Hide All Modules on Presence.

### ISSUE THREAD

**Issue by IntelliBR** [bugsounet/MMM-NewPIR#14]
Hi,
  
 It's possible utilize this module to hide all modules when detect presence and show all modules when not detect nothing ? And remove the timeout.

**Comment by bugsounet** [comment]
hi, i think it's possible by setting this config : 
```js
delay: 24 * 60 * 60 * 1000
```
delay will be set for one day
```js
reverseValue: true
```
and this config reverse sensor value

so:
 i think, timeout is one day means +/- desactivate.
if you want 2 days : replace 24 by 48
and if you reverse value sensor, you should have your wanted result

**Comment by IntelliBR** [comment]
> hi, i think it's possible by setting this config :
> 
> ```js
> delay: 24 * 60 * 60 * 1000
> ```
Change to 1 day, but thats okay, because i can change de value counter to false.
> 
> delay will be set for one day
> 
> ```js
> reverseValue: true
> ```
> 
> and this config reverse sensor value
> 
But, the reverse didn't work.... :( . Only reset de counter on presence, but not hide de modules.

**Comment by bugsounet** [comment]
sorry, so i can't do this, It's the reverse of MMM-NewPIR program.
Eventually Fork this program and modify it to make your own version

**Comment by IntelliBR** [comment]
It's a good ideia. MMM-NewPirReverse ! :) 

Thanks @bugsounet
