### ISSUE TITLE
This is not an error

### ISSUE THREAD

**Issue by tanhpkb** [bugsounet/MMM-NewPIR#15]
help me. how when i run mmm-youtube then mmm-newpir delay the time..and when i stop mmm-youtube then mmm-newpir works again

**Comment by bugsounet** [comment]
hi,
I can't integrate all specific event listener for youtube/spotify/...
but i have integered an incomming listener event to this module. (USER_PRESENCE)

you can use [this module](https://github.com/eouia/MMM-NotificationTrigger) module to reset MMM_NewPIR when YouTube is active

you have to program it to receive all youtube event and send notification to MMM-NewPIR by using:
```js
this.sendNotification("USER_PRESENCE", true)
```
or
```
notification to send : "USER_PRESENCE"
payload to send : true
```

**Comment by tanhpkb** [comment]
thank you..when i use this .sendNotification ("USER_PRESENCE", right into mmm-youtube..when mmm-youtube works.mmm-newpir is refreshing time delay.but not refreshing delay time during the time I watched youtube..how do mmm-newpir refresh the time delay until i stop youtube..thank you

**Comment by bugsounet** [comment]
eventually, increase delay time to  5 * 60 * 1000 (5 mins) or more
I can't modify it for this, just because i can't read YT state

but ... if you use MMM-AssistantMk2, AMk2 Pir Addon , and next version of Assistant2Display, it will be correct ;)
just wait and see
