### ISSUE TITLE
epoll error on startup while starting in serveronly mode

### ISSUE THREAD

**Issue by ProtoxiDe22** [bugsounet/MMM-NewPIR#16]
hello, i tried this module but when starting in serveronly mode i get this error in the node console, then the application exits 
`node: symbol lookup error: /home/pi/magicmirror/modules/MMM-NewPIR/node_modules/epoll/build/Release/epoll.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE
`
this does not happen when starting via npm start

**Comment by bugsounet** [comment]
Hi,
I think you don't install module. Because this message mean sensor module is not installed. 
Try install module by npm install

**Comment by ProtoxiDe22** [comment]
i tried npm install again in the module folder, nothing was updated, and i don't think that's the problem because when i run magicmirror with `npm start` this error is not thrown. this only occurs when running magicmirror via `node serveronly` i think this is something related to epoll trying to do something with electron, which isn't started up if you only start the server

**Comment by bugsounet** [comment]
v3.0.0 is out. please update this module if needed
