### ISSUE TITLE
Screensaver when all modules are hidden

### ISSUE THREAD

**Issue by mazeemsk** [bugsounet/MMM-NewPIR#17]
I want to add a screensaver when all module are hidden. Is there any possibility to play a slideshow or a video when modules are hidden and presence is not detected by sensor ?. https://github.com/AgP42/MMM-SmartWebDisplay This module can be used for screensaver purpose. Any webpage with pictures/slideshow or video can be played by using this.

Thanks.

**Comment by bugsounet** [comment]
Hi,
sorry, this program can't do this.
i can't integrate it, need to rewrite a lot of code for this.
you can fork my program for pir sensor detect and modify it
or my [pir](https://github.com/bugsounet/addons/blob/master/pir/pir.js) library in my addons repository to create your own module
