### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by tanhpkb** [bugsounet/MMM-NewPIR#21]
the new version doesn't seem to turn off my tv screen at all..I want when the timer runs out ... the hidden modules and the video signal are also disabled my TV is completely off like the previous version ..help me. thanks

**Comment by bugsounet** [comment]
hi, i update `MMM-NewPIR` module.

try update with:
```sh
cd ~/MagicMirror/modules/MMM-NewPIR
git pull
```
and restart your mirror
