### ISSUE TITLE
Sensor (?) issue

### ISSUE THREAD

**Issue by magicmirror7** [bugsounet/MMM-NewPIR#25]
Hi, I have problem with module, maybe someone can help me..

log:

> [NewPIR] Initialize...
> [NewPIR] Init Display: Done.
> [NewPIR] Init Governor: Desactivated.
> [NewPIR] Sensor Active: pin 21
> [NewPIR] Initialize Complete Version: 2.3.1
> [ERROR] (node:4195) [DEP0005] DeprecationWarning: Buffer () is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> [ERROR] (node:4195) [DEP0005] DeprecationWarning: Buffer () is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> [NewPIR] Display -- Actual: true - Wanted: true

My PIR SENSOR: HC-SR505

**Comment by bugsounet** [comment]
strange ... i don't use buffer()

**Comment by magicmirror7** [comment]
I deleted module and did a fresh install, now its working but only one time after launching MagicMirror.. Do you have any idea what might cause this?

**Comment by bugsounet** [comment]
v3.0.0 is out. please update this module if needed
