### ISSUE TITLE
prevent display sleeping before presence check?

### ISSUE THREAD

**Issue by robotfish42** [bugsounet/MMM-NewPIR#27]
I'm not sure if this is actually a bug I'm experiencing or if it's the intended functionality, but the way the module's working for me isn't quite what I expected. It seems to tick down to the set timeout, go to sleep, and then wake back up if the presence sensor is triggered. If the sensor is triggered at any time during the countdown, the countdown isn't reset, and if the sensor is in the high state at the moment the countdown ends, it still turns the display off and then immediately back on. Is there a way to have the module continue to check the sensor while the display is awake, and not go to sleep if there's someone in the room? Thanks

**Comment by bugsounet** [comment]
Hi, normaly i code this : 

* if presence detected : reset delay counter
* if screen is sleeping: wakeup it

try with `debug` feature for see in console what happen

**Comment by robotfish42** [comment]
A system reboot solved the error somehow. Now seeing the expected behaviour. Thanks!

**Comment by bugsounet** [comment]
perfect so ;)
