### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Rubberdauck** [bugsounet/MMM-NewPIR#3]
Not really sure what I did wrong here but I followed the steps in installation and added the configuration into the config.js file like this.

```
{
	module: 'MMM-NewPIR',
        config: {
		useSensor: false, // set to false if you don't use sensor
		sensorPin: 21, // sensor pin out
                delay: 10 * 1000, // delay for time out
                turnOffDisplay: true, // turn off display
                EconomyMode: true, // hide all modules
		Governor : "" // Set CPU Governor : "conservative"  "ondemand"  "userspace"  "powersave"  "performance" or set "" for no change
        }
},
```

I put it to useSensor false to test if it is working but nothing happens even after 10 seconds. Is there anything I'm doing wrong here?

**Comment by bugsounet** [comment]
hi, can you add `debug: true,` in `config {}`
and give me console log after timeout  please ?

what is for platform ?

**Comment by Rubberdauck** [comment]
Like this?

```
		{
			module: 'MMM-NewPIR',
		        config: {
				useSensor: true, // set to false if you don't use sensor
				sensorPin: 12, // sensor pin out
		                delay: 10 * 1000, // delay for time out
		                turnOffDisplay: true, // turn off display
		                EconomyMode: true, // hide all modules
				debug: true,
				Governor : "" // Set CPU Governor : "conservative"  "ondemand"  "userspace"  "powersave"  "performance" or set "" for no change
		        }
		},
```

Also how do i pull up the console log? Sorry I'm very new to magicmirror and i'm using raspberry pi4.

**Comment by Rubberdauck** [comment]
After looking around I've monitored it via "pm2 logs mm" and tested that the sensor is working. There is no timeout that turns off the display. I've also set the delay to be 1 second.

[03:12:53.457] [LOG]    [NewPIR] Initialize...
[03:12:53.493] [LOG]    [NewPIR] Init Display: Done.
[03:12:53.495] [LOG]    [NewPIR] Init Governor : Desactived.
[03:12:53.495] [LOG]    [NewPIR] Sensor Active: pin 12
[03:12:53.496] [LOG]    [NewPIR] Initialize Complete.
[03:12:53.764] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
[03:13:49.812] [LOG]    [NewPIR] Sensor read value: 1
[03:13:49.848] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
[03:13:52.034] [LOG]    [NewPIR] Sensor read value: 0
[03:24:23.408] [LOG]    [NewPIR] Sensor read value: 1
[03:24:23.465] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
[03:24:25.621] [LOG]    [NewPIR] Sensor read value: 0
[03:24:26.738] [LOG]    [NewPIR] Sensor read value: 1

**Comment by bugsounet** [comment]
hi, This module was created for RPI3
I have no RPI4 for test
My colleague will debug under RPI4 as soon as possible

**Comment by bugsounet** [comment]
hi, we test with RPI4
RPI3 commands for sleep screen is not compatible with RPI4.
I will upgrade it soon

Actually it can just turn off modules but not sleep mode

**Comment by przypieczony** [comment]
Hello.

I have exactly the same issue and I have Raspberry Pi 3B. I've tried to debug this, but I am not JS expert. However it looks to me like the node_helper.js is not communicating with core module script.

I can help with debug, but I need some guides how to do so.

**Comment by bugsounet** [comment]
I test a fresh install
[13:56:48.010] [LOG]    { sensor: true, pin: 21, display: true, governor: '', debug: true }
[13:56:48.159] [LOG]    call pirStatus script
[13:56:49.976] [LOG]    [NewPIR] Wake Up Detected.
[13:56:50.136] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
[13:57:28.484] [LOG]    [NewPIR] Sensor read value: 1
[13:57:28.602] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
[13:57:29.909] [LOG]    [NewPIR] Sensor read value: 0
[13:57:33.859] [LOG]    [NewPIR] Sensor read value: 1
[13:57:33.979] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
[13:57:35.291] [LOG]    [NewPIR] Sensor read value: 0
[13:57:45.024] [LOG]    [NewPIR] Sensor read value: 1
[13:57:45.091] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
[13:57:46.465] [LOG]    [NewPIR] Sensor read value: 0
[13:57:52.483] [LOG]    [NewPIR] Sensor read value: 1
[13:57:52.658] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true

seems worked, and call pirStatus

my conf : 
```
                {
                        module: 'MMM-NewPIR',
                        position: 'top_left',
                        config: {
                                debug: true,
                                useSensor: true,
                                sensorPin: 21,
                                delay: 5 * 60 * 1000,
                                turnOffDisplay: true,
                                ecoMode: true,
                                governor: ""
                        }
                },
```

**Comment by bugsounet** [comment]
I will inspect more ...
Actually i work around MMM-AssistantMk2 issue

**Comment by bugsounet** [comment]
i work around this,
i make update
If you want to test
`git pull && npm isntall`

**Comment by przypieczony** [comment]
Hello. I've just tested your latest change and unfortunately it still does not work. However I made some debugging and find out that sending notifications from node_helper.js to MMM-NewPIR.js are not working. I make a debug print inside `socketNotificationReceived` function within MMM-NewPIR.js which never show up in logs:
```    socketNotificationReceived: function (notification, payload) {
      console.log("Print notification:" + notification)
      switch(notification) {
        case "RESET_COUNTER":
```

I also made debug print in node_helper.js in order to check if notification sent:
```
   pirStatus: function() {
    var self = this
    this.pir = new Gpio(this.conf.pin, 'in', 'both')
    this.pir.watch(function (err, value) {
      if (self.conf.debug) console.log("[NewPIR] Sensor read value: " + value)
      if (value == 1) {
        console.log("Should send RESET_COUNTER")
        self.sendSocketNotification("RESET_COUNTER")
```

Logs:
```0|MagicMir | [NewPIR] Sensor read value: 1
0|MagicMir | [19:12:29.839] [LOG]    Should send RESET_COUNTER
0|MagicMir | [19:12:29.897] [LOG]    
0|MagicMir | [NewPIR] Display -- Actual: true - Wanted: true
0|MagicMir | [19:12:33.068] [LOG]    
0|MagicMir | [NewPIR] Sensor read value: 0
```

**Comment by sergge1** [comment]
The same for me - module does not turn off/on my display.

Raspberry Pi 3 B+, display over HDMI.
Raspbian Buster, clean fresh install.

**Comment by bugsounet** [comment]
ok, script core is correct

my mismake is [default config](https://github.com/bugsounet/MMM-NewPIR#configuration).

if position is  not set, counter don't works.
EconomyMode don't exist -- should be ecoMode
Governor don't exist -- should be governor

I correct it
sorry

**Comment by przypieczony** [comment]
I can confirm it works as expected now.

Thanks for the fix :).

**Comment by bugsounet** [comment]
Perfect, sorry for my mismake config.
Thanks for your report!
