### ISSUE TITLE
two instances of magic mirror and it'll confuse MMM-NewPIR

### ISSUE THREAD

**Issue by irsx02** [bugsounet/MMM-NewPIR#32]
Hi,
 I ran into this bug and perhaps someone may have some insight.    I'm debugging an unrelated module for Magic Mirror, and I noticed if I run two instances of MM, the clock/countdown gets confused and displays both time values.    

 So, I have one Magic Mirror instance running by default on startup (I assume launched by pm2.)  I also manually started another instance of MM using Chromium (localhost:8080, so I can read the js console for the other module)    Since there are now two instances, the timer bounces between the time remaining for the pm2 instance and the Chromium instance.  It'll switch off between both time remaining values.   Which would be fine if both timers can reset if I wave my hand in front of my PIR.   I'm debugging, so I close out and restart chromium again.  But when that happens, the Chromium instance of MMM-NewPIR's timer will not reset, and my screen will eventually turn off once time runs out.   No resetting that timer.

 Quite annoying.   Is there a way to set up some global variable or shared variable between all instances to use the same countdown value? 
 
 Notes:  Latest MagicMirror and New-PIR v3 versions via git pull.
   Raspberry Pi 3B  (not B+) 
   Raspian Pi OS
   Some cheap PIR (that works fine) running on GPIO 21.
   Using displayStyle: "SemiCircle",  because frankly, it looks good.
   Running "pm2 restart MagicMirror"  of course, will fix the problem. 
   Running "pm2 log" will show  both [NewPIR] Callback Notification: SCREEN_TIMER 02:52
                                                          [NewPIR] Callback Notification: SCREEN_TIMER 01:22
                 time remaining values inside the logs.  One time is from Chromium, other from pm2.  Both are counting down, even though I closed the Chromium session.   And yes, I can see the "[PIR] Sensor read value: 1" when I wave my hand in front of my PIR.  It'll reset the Magic Mirror instance's countdown(I think, i may mix the timers up.)   But not the (already closed) Chromium countdown timer. 
 
   Thanks,
 
     IRSX

**Comment by bugsounet** [comment]
I know about this bug, I haven't found a way to fix it.

It is +/- the same thing that you launch MagicMirror 2 times with 2 different programs but displayed on a single screen

if you want to have a live screen feedback use VNC instead
