### ISSUE TITLE
Turn on display delay

### ISSUE THREAD

**Issue by uros76** [bugsounet/MMM-NewPIR#34]
Hi. First, tnx for all the great work with this plugin! 

Is it possible to add a parameter that would allow the plugin to turn on the screen with a defined delay after the sensor passes signal? Or, maybe a parameter that I can specify the time of not accepting sensor signal after the screen goes off. 

It all works great for me as it is, just would like to add some delay before turning on the screen. Currently, mirror glass doesn't really do the job (not serving mirror function) since the sensor/plugin is always turning on the screen behind it :). With added start delay I could see myself in the mirror for a while. 

Is this possible?

**Comment by bugsounet** [comment]
Hi, thanks for your feedback ;)

but sorry it's not coded actually but i will pin it with enhancement

**Comment by hec59** [comment]
Hi. Easiest PIR module to install by far. Only issue I have is the screen wakes back up after about 15 seconds, even though PIR is covered. Any ideas?

**Comment by bugsounet** [comment]
it's planned, i finish the touch screen support and i will do it

**Comment by bugsounet** [comment]
Good news: i have coded it,

Bad news: i can't release it at now, because i have no PIR sensor for testing... (I'm not at home)

If you want to test contact me with Telegram

**Comment by hec59** [comment]
> Good news: i have coded it,
> 
> Bad news: i can't release it at now, because i have no PIR sensor for testing... (I'm not at home)
> 
> If you want to test contact me with Telegram

I can try it out and reply with results, cheers

**Comment by bugsounet** [comment]
Try this:

```sh
cd ~/MagicMirror/modules/MMM-NewPIR
git checkout -f dev
npm run update
cd node_modules/@bugsounet/
rm -rf pir
git clone https://github.com/bugsounet/pir
cd pir
npm install
cd ~/MagicMirror
```

in NewPIR configuration add this in `pir:{}` field
`delayed: 15000`

Sample:
```js
      pir: {
        usePir: true,
        gpio: 21,
        reverseValue: false,
        delayed: 15000
      },
```
don't forget coma before lasted feature
`delayed` value is in ms

to Reverse Back to master branch after testing
```sh
cd ~/MagicMirror/modules/MMM-NewPIR
git checkout -f dev
npm run update
```

Thank for your help

**Comment by hec59** [comment]
I gather I have to add the delayed: 15000 to the MM config file too? Let me know CheersSent from my Galaxy
-------- Original message --------From: Bugsounet - Cédric <notifications@github.com> Date: 29/12/2020  15:10  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display delay (#34) 
Try this:
cd ~/MagicMirror/modules/MMM-NewPIR
git checkout -f dev
npm run update
cd node_modules/@bugsounet/
rm -rf pir
git clone https://github.com/bugsounet/pir
cd pir
npm install
cd ~/MagicMirror
in NewPIR configuration add this in pir:{} field
delayed: 15000
Sample:
      pir: {
        usePir: true,
        gpio: 21,
        reverseValue: false,
        delayed: 15000
      },
don't forget coma before lasted feature
delayed value is in ms
to Reverse Back to master branch after testing
cd ~/MagicMirror/modules/MMM-NewPIR
git checkout -f dev
npm run update
Thank for your help

**Comment by bugsounet** [comment]
only on MM config of MMM-NewPIR

**Comment by hec59** [comment]
Ok. I've tried this out and the screen still activates after about 15 to 20 seconds, even when PIR is covered.Sent from my Galaxy
-------- Original message --------From: Bugsounet - Cédric <notifications@github.com> Date: 29/12/2020  15:39  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display delay (#34) 
only on MM config of MMM-NewPIR

**Comment by bugsounet** [comment]
I will try at home tomorrow

Normally the screen will turn on after 'delayed' value

And turn off after delay turn off screen

**Comment by hec59** [comment]
It turns on, but not by PIR activation.Sent from my Galaxy
-------- Original message --------From: Bugsounet - Cédric <notifications@github.com> Date: 29/12/2020  15:56  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display delay (#34) 
I will try at home tomorrow
Normally the screen will turn on after 'delayed' value
And turn off after delay turn off screen

**Comment by bugsounet** [comment]
ok i recode some part and release it

now you can enjoy this:

if your screen is off:
the screen turn on with delayed tme
if your screen is on:
reset the timer

see new config in `screen:{}` with `delayed` feature

**Comment by hec59** [comment]
Is there no way the screen will come on with just the pir or would putting in a timer of 1 day be ok Sent from my Galaxy
-------- Original message --------From: Bugsounet - Cédric <notifications@github.com> Date: 31/12/2020  11:44  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display delay (#34) 
Closed #34.

**Comment by bugsounet** [comment]
it's the main feature ... if not work your sensor is not setup correctly

I just code the @uros76 wanted feature

**Comment by hec59** [comment]
I have both potentiometers set to low. The screen still wakes up, even though the PIR hasn't been crossed. Should I change the value of the sleep time so it doesn't wake up unless PIR is crossed?Sent from my Galaxy
-------- Original message --------From: Bugsounet - Cédric <notifications@github.com> Date: 31/12/2020  13:26  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display delay (#34) 
it's the main feature ... if not work your sensor is not setup correctly
I just code the @uros76 wanted feature
