### ISSUE TITLE
not reading sensor

### ISSUE THREAD

**Issue by Kai2508** [bugsounet/MMM-NewPIR#4]
I have the problem that the monitor is switched off but the sensor is not read
There is my config.
```
{
	module: 'MMM-NewPIR',
	position: 'top_left',
        config: {
		useSensor: true, // use sensor
		sensorPin: 19, // sensor pin out
                delay: 30 * 1000, // delay for time out
                turnOffDisplay: true, // turn off display
                ecoMode: false, // hide all modules
		debug: true, // debug mode
		governor : "", // Set CPU Governor : "conservative"  "ondemand"  "userspace"  "powersave"  "performance" or set "" for no change
        }
},
```
I have tested with another script if the sensor works and it does

The log looks like this:

0|mm       | [12:26:24.991] [LOG]    [NewPIR] Initialize...
0|mm       | [12:26:25.067] [LOG]    [NewPIR] Init Display: Done.
0|mm       | [12:26:25.070] [LOG]    [NewPIR] Init Governor : Desactived.
0|mm       | [12:26:25.071] [LOG]    [NewPIR] Sensor Active: pin 19
0|mm       | [12:26:25.072] [LOG]    [NewPIR] Initialize Complete.
0|mm       | [12:26:25.114] [LOG]    [NewPIR] Display -- Actual: true - Wanted: true
0|mm       | [12:26:54.484] [LOG]    [NewPIR] Display -- Actual: true - Wanted: false
0|mm       | [12:26:54.539] [LOG]    [NewPIR] Display OFF.

**Comment by bugsounet** [comment]
Hi,
I only test for my personal use with sensor [HC-SR501 PIR](https://www.amazon.fr/gp/product/B01C6O9C38/ref=ppx_yo_dt_b_asin_title_o05_s00)

I will update NewPIR for "universal PIR" script soon

**Comment by Kai2508** [comment]
I also use a [HC-SR501](https://www.berrybase.de/raspberry-pi-co/raspberry-pi/module-sensoren/hc-sr501-pir-sensor-infrarot-bewegungsmelder?c=343) but not exactly the same one, my has a slightly different board

**Comment by bugsounet** [comment]
try to my default pin, i use this pin

what pir module works ? (i will inspect)

**Comment by Kai2508** [comment]
It´s the same problem 

I used this script to test if the sensor works
```
import RPi.GPIO as GPIO
import time
import datetime
import os

print "BEWEGUNGSMELDER"
print ""

#Board Mode: Angabe der Pin-Nummer
GPIO.setmode(GPIO.BOARD)

#GPIO Pin definieren fuer den Dateneingang vom Sensor
PIR_GPIO = 21
GPIO.setup(PIR_GPIO, GPIO.IN)

def MOTION(PIR_GPIO):
     os.system("echo  \"Bewegung erkannt\"")

print "%s - Warten auf Bewegung" % datetime.datetime.now()  
try:
     GPIO.add_event_detect(PIR_GPIO, GPIO.RISING, callback=MOTION)
     while 1:
          time.sleep(60)
except KeyboardInterrupt:
	GPIO.cleanup()
```

**Comment by bugsounet** [comment]
[Code](https://github.com/bugsounet/MMM-NewPIR/blob/master/node_helper.js#L62)
but i don't check err, maybe there is error
or you run 2 scripts (mine / yours) on same time

**Comment by bugsounet** [comment]
i work around this,
i make update
If you want to test
`git pull && npm isntall`

**Comment by renzo79** [comment]
Helllo,


At first thanks for your module and your Help. You can thinks make happen which I can not in my dreams. .

I had the same problems with your script and I´ve updated it like in the workaround in the post before. But now the MagicMirror is not starting anymore:

pi@raspberrypi:~/MagicMirror $ npm start debug

> magicmirror@2.10.1 start /home/pi/MagicMirror
> ./run-start.sh "debug"

[11:08:46.654] [LOG]    Starting MagicMirror: v2.10.1
[11:08:46.671] [LOG]    Loading config ...
[11:08:46.677] [LOG]    Loading module helpers ...
[11:08:46.680] [LOG]    No helper found for module: alert.
[11:08:46.681] [LOG]    No helper found for module: clock.
node: symbol lookup error: /home/pi/MagicMirror/modules/MMM-NewPIR/node_modules/epoll/build/Release/epoll.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.10.1 start: `./run-start.sh "debug"`
npm ERR! spawn ENOENT
 Thanks for your help

**Comment by bugsounet** [comment]
try this:

```sh
cd ~/MagicMirror/modules/MMM-NewPIR
rm package.json
rm package-lock.json
git checkout package.json
rm -rf node_modules
git pull
npm install
```

**Comment by renzo79** [comment]
Thanks!!!

That was fixing the problem

Best

**Comment by Kai2508** [comment]
I'm not quite sure how but I was able to solve the problem apparently it helped me to check everything again and reinstall the module.

Now it works without problems.
