### ISSUE TITLE
displayStyle "Bar" and "Line" only visible with other modules at the same position

### ISSUE THREAD

**Issue by xKrummy** [bugsounet/MMM-NewPIR#43]
I was playing around a bit with this module and i noticed that if i chose the displayStyle: "Bar"or "Line" then the bar is hidden from the MagicMirror (same goes for the timer with this style chosen)

If i place something else in the same position tab as the bar, then it is displayed again as well as the timer in this case.
For the other styles the issue does not appear.

My assumption: the Bar misses the config for it size. So if some other module it is present, it ca adopt that length, but if no other module is there the default bar length is 0.

**Comment by bugsounet** [comment]
corrected, sorry for very last response
