### ISSUE TITLE
Turn on display with click mouse or touch screen

### ISSUE THREAD

**Issue by giovamec** [bugsounet/MMM-NewPIR#44]
Thanks for the very nice module.
It is possible to turn on the monitor with the click of the mouse or with the touch screen and not only with the PIR sensor?
Gio

**Comment by bugsounet** [comment]
Good idea 💡

I will code it soon ;)

**Comment by bugsounet** [comment]
I have coded your wanted feature and it will be available with NewPIR v3.1.2

# TouchScreen Feature
You can use this feature with a mouse or your touch screen

* One Click on the screen: Will wake up the screen or restart your shutdown timer
* Double Click on the screen: Will turn off your screen

**Comment by giovamec** [comment]
Great.
regarding: "Double Click on the screen: Will turn off your screen"
I think there will always be parameters to activate the functionality to prevent an involuntary double click (especially with touch screen) from bringing the timer to zero. Or simply take it to 10 or 5 seconds for example. so that if there are no other clicks it will turn off after reduced time, otherwise the timer will reset as scheduled.
When you think it will be online with the changes

**Comment by bugsounet** [comment]
I purpose this:

  * one click on New_PIR module area will reset timer
  * double click on New_PIR area will turn on screen
  * one click on the screen if all modules is hidden will wake up the screen

New-Pir area is the module display (counter, presence, design count down) 

It's ok for you?

**Comment by bugsounet** [comment]
Finaly code this, I think it's really better

# TouchScreen Feature
You can use this feature with a mouse or your touch screen

* One Click on the NewPIR Area: will restart your shutdown timer
* Long Click on the screen: Will turn off your screen or Will turn on if needed (Toogle)

**Comment by bugsounet** [comment]
Note: enable UseTouch in the `screen :{}` field

**Comment by giovamec** [comment]
dear,
with the new "TouchScreen Feature" it is ok for mouse use, but it does not work with touch screen, probably because the long click is not a good solution! 
It might be useful/better a "double click" to make it turn on again.
what do you think about it?

**Comment by bugsounet** [comment]
I Will code the 2 modes so... Humm

**Comment by bugsounet** [comment]
added `touch:{}` and mode feature
another mode is added

see ReadMe file :)

**Comment by hec59** [comment]
Any joy on trying out the PIR only activation of screen after shutdown?Sent from my Galaxy
-------- Original message --------From: Bugsounet - Cédric <notifications@github.com> Date: 30/12/2020  10:20  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display with click mouse or touch screen (#44) 
added touch:{} and mode feature
another mode is added
see ReadMe file :)

**Comment by giovamec** [comment]
thanks, by tomorrow I'll try it and I'll let you know.

**Comment by giovamec** [comment]
Sorry for the delay, I checked and in mode 3 with the touch it is fine.
I just have to check why if it is off for a few hours, then it is slow to turn on. maybe it depends on some other setting :-)

**Comment by hec59** [comment]
Hi. How do I stop it turning on with the timer. And how do you adjust timer for a longer sleep. I only want it to turn on when activated by the PIR. Apart from this, its 100%Sent from my Galaxy
-------- Original message --------From: giovamec <notifications@github.com> Date: 05/01/2021  16:35  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display with click mouse or touch screen (#44) 
Sorry for the delay, I checked and in mode 3 with the touch it is fine.
I just have to check why if it is off for a few hours, then it is slow to turn on. maybe it depends on some other setting :-)

**Comment by giovamec** [comment]
maybe I expressed myself badly.
the module works perfectly. I don't want it to turn on after a few hours.
in my case, after it has turned off correctly if I leave it off after 3 or 4 hours and I go to touch the mirror to turn it back on it takes about 25 seconds. is a raspy 4 maybe there is something else going on in standby!?!? but I don't think it depends on the module. :-)

**Comment by hec59** [comment]
I have raspi4. After screen goes off, it turns on again after about 10 seconds or so. Here is a list of other modules on my mm.Calendar, moonphase, weather, Spotify,  news feed and screencast. Would any of these 'wake' the screen?Sent from my Galaxy
-------- Original message --------From: giovamec <notifications@github.com> Date: 05/01/2021  16:54  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Turn on display with click mouse or touch screen (#44) 
maybe I expressed myself badly.
the module works perfectly. I don't want it to turn on after a few hours.
in my case, after it has turned off correctly if I leave it off after 3 or 4 hours and I go to touch the mirror to turn it back on it takes about 25 seconds. is a raspy 4 maybe there is something else going on in standby!?!? but I don't think it depends on the module. :-)
