### ISSUE TITLE
Conflict with MMM-GoogleTasks

### ISSUE THREAD

**Issue by Dimasua** [bugsounet/MMM-NewPIR#47]
Hej,

thank you for your great work! The visual design of the module is just an eye-catcher! 👍 
After I set up the MMM-NewPIR module, I installed [MMM-GoogleTasks](https://github.com/jgauth/MMM-GoogleTasks) and that led to the graphical count down bar in the PIR module to disappear. The functionality as such (turning off and on the display) is working fine, however, something impacted the graphical output of the module. 

Can you please give a hint of what that could be?

**Comment by bugsounet** [comment]
i have corrected some similar bug yesterday

maybe is not updated to v3.1.2?

**Comment by Dimasua** [comment]
Just updated it, and the module now does not show up. Before it had displayed the last presence message. Now nothing.

**Comment by bugsounet** [comment]
this module is not update since 3 years ... and many module have problem with it
see [this issue](https://github.com/jgauth/MMM-GoogleTasks/issues/5)
