### ISSUE TITLE
NPM updates?

### ISSUE THREAD

**Issue by ezar** [bugsounet/MMM-NewPIR#51]
Hi @bugsounet ,

Thanks for revamp this module.

Can you help us with this alert?

<img width="677" alt="Screenshot 2021-01-02 at 08 04 08" src="https://user-images.githubusercontent.com/42736/103452581-4423ba00-4cd1-11eb-8f7d-be900d2fd94e.png">

**Comment by ezar** [comment]
I update package.json for use these versions, but I don't know if are stable!
Rgards,

**Comment by bugsounet** [comment]
really ? do you read the [ReadMe](https://github.com/bugsounet/MMM-NewPIR#update) !?

**Comment by ezar** [comment]
Ok! Thanks.
