### ISSUE TITLE
Works, but doesn't switch on

### ISSUE THREAD

**Issue by gkchim** [bugsounet/MMM-NewPIR#52]
Works well. timer resets after motion. But once the screen has been turned off, motion cannot turn the screen on, i have to manually use MMM-remoteControl.

Any advice please?

**Comment by bugsounet** [comment]
Hi, just because, many program is not compatible with RemoteControl (Pir, Assistant, *chatBot, ...)

**Comment by gkchim** [comment]
Hi @bugsounet , thank you very much for creating this awesome module. I wanted to know if i have incorrectly configured settings or installation.

the PIR sensor works to reset the countdown timer. However once the screen is off, if the PIR sensor senses movement, the screen does not switch on... is this supposed to happen?

Many thanks

**Comment by hec59** [comment]
It works for me, except when screen is off,  and no one near PIR, the screen still wakes up. I want it to stay off until PIR is activated Sent from my Galaxy
-------- Original message --------From: gkchim <notifications@github.com> Date: 12/01/2021  22:42  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Works, but doesn't switch on (#52) 
Hi @bugsounet , thank you very much for creating this awesome module. I wanted to know if i have incorrectly configured settings or installation.
the PIR sensor works to reset the countdown timer. However once the screen is off, if the PIR sensor senses movement, the screen does not switch on... is this supposed to happen?
Many thanks

**Comment by bugsounet** [comment]
Try this wiki part of another of my module but work too with NewPIR Module (same personal library used)

[There](https://github.com/bugsounet/MMM-Assistant2Display/wiki/pir#pir-module)

It allows to configurate or Check  your Pir Sensor

**Comment by hec59** [comment]
The sensor part works perfectly..I have value set to turn off screen after 30 seconds if no movement on PIR. then screen turns off. No sooner as its gone off its back on again, still with no movement detected by PIR. Its not the PIR thats turning the screen back on, so what could be making turn on again???Sent from my Galaxy
-------- Original message --------From: Bugsounet - Cédric <notifications@github.com> Date: 12/01/2021  22:49  (GMT+00:00) To: bugsounet/MMM-NewPIR <MMM-NewPIR@noreply.github.com> Cc: hec59 <darren_storey@yahoo.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [bugsounet/MMM-NewPIR] Works, but doesn't switch on (#52) 
Try this wiki part of another of my module but work too with NewPIR Module (same personal library used)
There
It allows to configurate or Check  your Pir Sensor
