### ISSUE TITLE
Uncaught TypeError: Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by sergge1** [bugsounet/MMM-NewPIR#8]
Started using this module for MM.
I have the following config:
<details><summary><b>Extract from config.js</b></summary>
<p>

```
		{
			module: 'MMM-NewPIR',
			disabled: false,
			config: {
				sensorPin: 11, // sensor pin out
				delay: 45 * 1000, // delay for time out
				turnOffDisplay: true, // turn off display
				EconomyMode: false, // hide all modules
				Governor: "" // Set CPU Governor : "conservative"  "ondemand"  "userspace"  "powersave"  "performance" or set "" for no change
			}
		},
```
</details></p>

<details><summary><b>Terminal LOG extract</b></summary>
<p>

```
[2020-02-05 23:30:21.322] [LOG]    [NewPIR] Initialize...
[2020-02-05 23:30:21.360] [LOG]    [NewPIR] Init Display: Done.
[2020-02-05 23:30:21.361] [LOG]    [NewPIR] Init Governor : Desactived.
[2020-02-05 23:30:21.363] [LOG]    [NewPIR] Sensor Active: pin 11
[2020-02-05 23:30:21.364] [LOG]    [NewPIR] Initialize Complete.
```
</details></p>

In console I see the following error emitted by MMM-NewPIR:
![Annotation 2020-02-05 233052](https://user-images.githubusercontent.com/49363121/73885057-c1e80700-486f-11ea-882b-a72da0b73dff.jpg)

**Comment by bugsounet** [comment]
you haven't set position in config. if you set debug mode... it display counter also
and so `position: 'top_left',` in config.js
